ignore:
  - "Sources/SwiftPlantUMLFramework/Presenting/PlantUMLBrowserPresenter.swift"
  - "Tests"
coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 5
    patch:
      default:
        target: 80
        threshold: null
    changes: false
